package ios.uikit;

import cpp.objc.NSString;
import cpp.objc.NSData;
@:objc
@:enum
@:native("UIGestureRecognizerState")
@:include("UIKit/UIKit.h")
extern abstract UIGestureRecognizerState(Int) from Int to Int {

	@:native("UIGestureRecognizerStatePossible")
	var UIGestureRecognizerStatePossible;

	@:native("//therecognizerhasnotyetrecognizeditsgesture")
	var //therecognizerhasnotyetrecognizeditsgesture;

	@:native("butmaybeevaluatingtouchevents.thisisthedefaultstateUIGestureRecognizerStateBegan")
	var butmaybeevaluatingtouchevents.thisisthedefaultstateUIGestureRecognizerStateBegan;

	@:native("//therecognizerhasreceivedtouchesrecognizedasthegesture.theactionmethodwillbecalledatthenextturnoftherunloopUIGestureRecognizerStateChanged")
	var //therecognizerhasreceivedtouchesrecognizedasthegesture.theactionmethodwillbecalledatthenextturnoftherunloopUIGestureRecognizerStateChanged;

	@:native("//therecognizerhasreceivedtouchesrecognizedasachangetothegesture.theactionmethodwillbecalledatthenextturnoftherunloopUIGestureRecognizerStateEnded")
	var //therecognizerhasreceivedtouchesrecognizedasachangetothegesture.theactionmethodwillbecalledatthenextturnoftherunloopUIGestureRecognizerStateEnded;

	@:native("//therecognizerhasreceivedtouchesrecognizedastheendofthegesture.theactionmethodwillbecalledatthenextturnoftherunloopandtherecognizerwillberesettoUIGestureRecognizerStatePossibleUIGestureRecognizerStateCancelled")
	var //therecognizerhasreceivedtouchesrecognizedastheendofthegesture.theactionmethodwillbecalledatthenextturnoftherunloopandtherecognizerwillberesettoUIGestureRecognizerStatePossibleUIGestureRecognizerStateCancelled;

	@:native("//therecognizerhasreceivedtouchesresultinginthecancellationofthegesture.theactionmethodwillbecalledatthenextturnoftherunloop.therecognizerwillberesettoUIGestureRecognizerStatePossibleUIGestureRecognizerStateFailed")
	var //therecognizerhasreceivedtouchesresultinginthecancellationofthegesture.theactionmethodwillbecalledatthenextturnoftherunloop.therecognizerwillberesettoUIGestureRecognizerStatePossibleUIGestureRecognizerStateFailed;

	@:native("//therecognizerhasreceivedatouchsequencethatcannotberecognizedasthegesture.theactionmethodwillnotbecalledandtherecognizerwillberesettoUIGestureRecognizerStatePossible//DiscreteGestures–gesturerecognizersthatrecognizeadiscreteeventbutdonotreportchanges(forexample")
	var //therecognizerhasreceivedatouchsequencethatcannotberecognizedasthegesture.theactionmethodwillnotbecalledandtherecognizerwillberesettoUIGestureRecognizerStatePossible//DiscreteGestures–gesturerecognizersthatrecognizeadiscreteeventbutdonotreportchanges(forexample;

	@:native("atap)donottransitionthroughtheBeganandChangedstatesandcannotfailorbecancelledUIGestureRecognizerStateRecognized")
	var atap)donottransitionthroughtheBeganandChangedstatesandcannotfailorbecancelledUIGestureRecognizerStateRecognized;


}